# P-ROC Game Description file for T2
PRGame:
    machineType: wpc
    numBalls: 3
PRFlippers:
    - flipperLwR
    - flipperLwL
PRBumpers:
    - slingL
    - slingR
    - bumperOne
    - bumper2
    - bumper3
    - bumper4
    - bumper5
PRSwitches:
    # **** Format ****
    # name:
    #   number: <number>
    #   type: <type>
    #
    #   <number> can be: SFx (Flipper switch, labeled Fx in WPC manual
    #                    SDx (Dedicated switch, labeled SDx in WPC manual
    #                    Sx  (Matrix switch, labeled x in WPC manual
    #   <type> can be: 'NO' (normally open.  This is the default; so no need to use this)
    #                  'NC' (normally closed.  Common for optos)
    flipperLwR:
        number: S11
        ballsearch: stop # stop: this switch prevents the ballsearch timer from even starting
    flipperLwL: 
        number: S12
        ballsearch: stop 
    coinL:
        number: SD1
    coinR:
        number: SD3
    exit: 
        number: SD5
    down: 
        number: SD6
    up: 
        number: SD7
    enter: 
        number: SD8
    startButton:
        number: S13
    tilt:
        number: S14
    trough1:
        number: S15
        ballsearch: reset # reset: this switch resets a ballsearch timer to occur X-seconds after this was seen
    trough2:
        number: S16
        ballsearch: reset 
    trough3:
        number: S17
        ballsearch: reset 
    outhole:
        number: S18
        ballsearch: reset 
    slamTilt:
        number: S21
    coinDoor:
        number: S22
    saucer:
        number: S24
        ballsearch: reset        
    outlaneL:
        number: S25
        ballsearch: reset 
    inlaneL:
        number: S26
        ballsearch: reset 
    inlaneR:
        number: S27        
        ballsearch: reset 
    outlaneR:
        number: S28
        ballsearch: reset
    LGate:
        number: S31
    RGate:
        number: S32      
    Ltarget1: 
        number: S33
        ballsearch: reset 
    Ltarget2: 
        number: S34
        ballsearch: reset 
    Ltarget3: 
        number: S35
        ballsearch: reset 
    Rtarget1:
        number: S36
        ballsearch: reset 
    Rtarget2:
        number: S37
        ballsearch: reset 
    Rtarget3: 
        number: S38
        ballsearch: reset 
    TopLane1:
        number: S41
        ballsearch: reset 
    TopLane2:
        number: S42
        ballsearch: reset 
    TopLane3:
        number: S43
        ballsearch: reset 
    TopLane4:
        number: S44
        ballsearch: reset 
    RampShot:
        number: S45
    slingR:
        number: S46
        ballsearch: reset 
    slingL:
        number: S47          
    bumperOne:
        number: S51
        ballsearch: reset
    bumper2:
        number: S52
        ballsearch: reset 
    bumper3:
        number: S53
        ballsearch: reset 
    bumper4:
        number: S54
        ballsearch: reset
    bumper5:
        number: S55
        ballsearch: reset 
    shooter:
        number: S78
        ballsearch: stop, reset
PRCoils:
    flipperLwRMain: 
        number: FLRM
    flipperLwRHold: 
        number: FLRH
    flipperLwLMain: 
        number: FLLM
    flipperLwLHold: 
        number: FLLH
    flipperEnable:
        number: G08
    saucer:
        number: C01
    gunKicker:
        number: C02
    outhole:
        number: C03
        ballsearch: True
    trough:
        number: C04
        ballsearch: True
    slingR:
        number: C05
    slingL:
        number: C06
    knocker:
        number: C07
    kickback:
        number: C08
        ballsearch: True
    plunger:
        number: C09
    lockTop:
        number: C10
        ballsearch: True
    gunMotor:
        number: C11
    knockDown:
        number: C12
        patterOnTime: 8
        patterOffTime: 2
    bumperOne:
        number: C13
    bumper2:
        number: C14
    bumper3:
        number: C15
    bumper4:
        number: C16
    bumper5:
        number: C17        
    flasherSlingR:
        number: C18
    flasherSlingL:
        number: C19
    flasherLockL:
        number: C20
    flasherGun:
        number: C21
    flasherRampR:
        number: C22
    flasherRampL:
        number: C23
    flasherBackglass:
        number: C24
    flasherTargets:
        number: C25
    flasherPopperL:
        number: C26
    flasherPopperR:
        number: C27
    dropTarget:
        number: C28
PRLamps:
    Ltarget1:
        number: L11
    Ltarget2:
        number: L12
    Ltarget3:
        number: L13
    shootAgain:
        number: L16
        tags: shoot_again
    Rtarget1:
        number: L21
    Rtarget2:
        number: L22
    Rtarget3:
        number: L23
    TopLane1:
        number: L24
    TopLane2:
        number: L25
    TopLane3:
        number: L26
    TopLane4:
        number: L27
    LRib1:
        number: L41
    LRib2:
        number: L42
    LRib3:
        number: L43
    LRib4:
        number: L44
    LRib5:
        number: L45
    LRib6:
        number: L46
    LRib7:
        number: L47
    RRib1:
        number: L51
    RRib2:
        number: L52
    RRib3:
        number: L53
    RRib4:
        number: L54
    RRib5:
        number: L55
    RRib6:
        number: L56
    RRib7:
        number: L57
    topInsertGI:
        number: G01
    playfieldLeftGI:
        number: G02
    playfieldRightGI:
        number: G03
    bottomInsertGI:
        number: G05
